----------------------------------- ----------------------------------- ----------------------------------- 
----------------------------------- ESPACIO PARA BANNER DE LA MAESTRIA -----------------------------------
----------------------------------- ----------------------------------- ----------------------------------- 

# Revisión de Algebra Lineal

Este *cuaderno* es un breve repaso sobre vectores y matrices, y su implementación en `Python` utilizando la librería **[Numpy](http://www.numpy.org/)**, temas fundamentales para el desarrollo de buena parte de las actividades de este curso. **NO** es necesario que usted edite el archivo o que haga una entrega. Sin embargo, es libre de modificarlo editando celdas de texto (celdas *Markdown*) o las celdas de código (`celdas con código ejecutable están en gris`). Esta puede ser una buena forma de aprender nuevas funcionalidades del cuaderno, o experimentar variaciones en los códigos de ejemplo. 

Al final encontrará algunos ejercicios asociados a los contenidos del cuaderno para que los resuelva por su propia cuenta (no debe entregarlos). Si tiene dudas sobre alguno de los contenidos o alguno de los ejercicios, consulte con el tutor. Si tiene dudas sobre el uso de `Python`, puede revisar el Tutorial `Introducción a Python` que se encuentra en la plataforma del curso.


## Vectores

Un vector es una serie de números que tienen un orden preestablecido, y podemos identificar cada número por un índice que indica ese orden. Podemos pensar en los vectores como las coordenadas de puntos en el espacio, con cada elemento indicando la ubicación a lo largo de un eje diferente. Existen dos tipos de vectores, los vectores fila:

$$ a = \begin{bmatrix} 5 & 9 & 7 \end{bmatrix}  $$

 y los vectores columna:

$$ b= \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $$


En `Python`, podemos representar a un *vector* con una *lista*, o preferiblemente, con un *array* de [Numpy](http://www.numpy.org/) :

- Vector como *lista* de `Python`

In [84]:
a = [5, 9, 7]
a

[5, 9, 7]

- Vectores como *array* de [Numpy](http://www.numpy.org/) 

In [85]:
import numpy as np # Recordemos llamar la librería numpy

b = np.array([1, 2, 3]) 
b

array([1, 2, 3])

    o de forma similar utilizando la función `arange`:

In [86]:
c = np.arange(1, 8) 
c

array([1, 2, 3, 4, 5, 6, 7])

- Crear un vector con todos los elementos iguales a uno, usando  la función `ones` y el número de elementos:

In [97]:
d = np.ones(3) 
d

array([1., 1., 1.])

 - Transformar un vector fila en un vector columna con la función de transposición, que denotamos con los símbolos $T$ o $'$. Así, el transpuesto del vector $a$ es:

    $$ a = \begin{bmatrix} 5 \\ 9 \\ 7 \end{bmatrix}  $$

    En `Python` usamos la función `transpose`:

In [98]:
np.transpose(a)

array([5, 9, 7])

### Operaciones con vectores

Para operar sobre vectores debemos  tener en cuenta ciertas particularidades de operación.

#### Suma y resta

Cuando *sumamos* dos vectores, el resultado es la suma de cada elemento del vector:


$$ \begin{split}x + y
=
\left[
\begin{array}{c}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{array}
\right]
+
\left[
\begin{array}{c}
     y_1 \\
     y_2 \\
    \vdots \\
     y_n
\end{array}
\right]
=
\left[
\begin{array}{c}
    x_1 + y_1 \\
    x_2 + y_2 \\
    \vdots \\
    x_n + y_n
\end{array}
\right]\end{split}$$


En `Python`:

In [89]:
x = np.array([1, 5]) 
y = np.array([2, 4])

x+y


array([3, 9])

Si utilizamos dos listas:

In [90]:
[1, 2, 3, 4] + [2, 4, 6, 8]

[1, 2, 3, 4, 2, 4, 6, 8]

En este caso `Python` no suma los elementos, sino que concatena las listas. Esta es una de las principales razones por las que preferimos utilizar arrays en [Numpy](http://www.numpy.org/) .


La resta funciona de forma análoga a la suma:

$$ \begin{split}x - y
=
\left[
\begin{array}{c}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{array}
\right]
-
\left[
\begin{array}{c}
     y_1 \\
     y_2 \\
    \vdots \\
     y_n
\end{array}
\right]
=
\left[
\begin{array}{c}
    x_1 - y_1 \\
    x_2 - y_2 \\
    \vdots \\
    x_n - y_n
\end{array}
\right]\end{split}$$

En `Python`:

In [91]:
x - y

array([-1,  1])

#### Multiplicación por un escalar
La *Multiplicación por un escalar* es una operación que toma un número $\alpha$ (un escalar), y un vector $x$, para producirun nuevo vector donde cada elemento del vector $x$ es multiplicado por el número $\alpha$.

$$\begin{split}\alpha x
=
\left[
\begin{array}{c}
    \alpha x_1 \\
    \alpha x_2 \\
    \vdots \\
    \alpha x_n
\end{array}
\right]\end{split}$$

En `Python`:

In [92]:
x * 4

array([ 4, 20])

In [93]:
y * 6

array([12, 24])

#### Producto escalar 

El producto escalar, también  conocido como el producto interior, de dos vectores se define como la suma de los productos de sus elementos. Solemos representarlo matemáticamente como $< x, y >$ o $x'y$, donde $x$ e $y$ son dos vectores:

$$< x, y > = \sum_{i=1}^n x_i y_i$$



En `Python` la función `dot` de [Numpy](http://www.numpy.org/) permite hacer esta operación: 

In [94]:

np.dot(x, y)

22

de forma equivalente, podemos hacer la suma del producto:

In [95]:
sum(x * y)

22

Un concepto derivado del producto escalar es que decimos que dos vectores son *ortogonales*  cuando su producto escalar es 0.

In [96]:
x = np.array([3, 4])
y = np.array([4, -3])

np.dot(x, y)

0

#### Norma de un vector
Relacionado al concepto de producto escalar aparece el concepto de  *norma vectorial*. La norma de un vector x (que denotamos con $||x||$) es una medida de la longitud del vector. Formalmente una norma es una función $f: \mathbb{R}^n \rightarrow \mathbb{R}$ que satisface las siguientes propiedades:

1. **No negativa.** Para todo $x\in\mathbb{R}^n,\ f(x)\geq0$.
2. **Definida.** $f(x)=0$ si y solo si $x=0$.
3. **Homogeneidad.** Para todo $x\in\mathbb{R}^n,\ c\in\mathbb{R},\ f(cx)=|c|f(x)$
4. **Desigualdad triangular.** Para todo $x, y \in\mathbb{R}^n,\ f(x+y)\leq f(x) + f(y)$ 

Usualmente utilizamos la norma $l_2$, también conocida como Euclideana. Esta se define como:

$$||x||_2= \sqrt{\sum_{i=1}^nx^Tx} \sqrt{\sum_{i=1}^nx_i^2}$$ 

Note que $||x||_2^2=x^Tx$. 

En `Python` podemos usar la función `sqrt` y `dot`:

In [67]:
np.sqrt(np.dot(x, x))

5.0

o directamente usando la función `linalg.norm`:

In [68]:
np.linalg.norm(x)

5.0

Otro ejemplo de norma es la norma $l_1$:

$$||x||_1= |\sum_{i=1}^nx_i^2|$$

## Matrices

Una *matriz* es un arreglo rectangular de números (llamados entradas o elementos de la matriz) que están  ordenados en filas y columnas. Por ejemplo, la matriz A:

$$A=\begin{bmatrix}0 & 1& \\-1 & 2 \\ -2 & 3\end{bmatrix}$$

El número de filas y columnas nos da el orden de la matriz. Así, la matriz A es de orden 3x2, es decir, es una matriz con 3 filas y 2 columnas.

Entonces una matriz A `n × k` es un arreglo con n filas y k columnas, que podemos representarla de forma general de la siguiente manera:

$$\begin{split}A =
\left[
\begin{array}{cccc}
    a_{11} & a_{12} & \cdots & a_{1k} \\
    a_{21} & a_{22} & \cdots & a_{2k} \\
    \vdots & \vdots &  & \vdots \\
    a_{n1} & a_{n2} & \cdots & a_{nk}
\end{array}
\right]\end{split}$$

Donde $a_{nk}$ representa el elemento típico de la matriz ubicado en la  n-ésima  fila de la k-ésima columna. 

Notemos que los vectores son casos particulares de matrices donde n o k son iguales a 1. En el caso de n=1, tenemos un *vector fila*, mientras que en el caso de k=1 tenemos un *vector columna*.

En `Python` creamos una matriz  utilizando una lista de vectores fila:

In [50]:
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])

B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])

### Matrices especiales

#### Matriz cuadrada

Una matriz cuadrada es una matriz que tiene el mismo número de filas que de columnas. Por ejemplo, la matriz A definida anteriormente. 

En `Python` obtenemos  la dimensión  de una matriz, el número de filas y columnas, con la función `shape`:

In [53]:
A.shape

(3, 3)

#### Matriz identidad

La matriz identidad  es una matriz cuadrada cuyos elementos de la diagonal principal son (1) y el resto de los elementos ceros (0). Esta matriz la denotamos con la letra `I`.

Por ejemplo, la matriz identidad de 3x3 sería la siguiente:

$$I=\begin{bmatrix}1 & 0 & 0 & \\0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix}$$

En `Python` utilizamos la función `eye`:

In [54]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Matriz transpuesta

La matriz transpuesta es aquella en que las filas se transforman en columnas y las columnas en filas. Se representa con los símbolos $T$ o $'$. Por ejemplo:

$$\begin{bmatrix}a & b & \\ c & d & \\ e & f & \end{bmatrix}^T=\begin{bmatrix}a & c & e &\\b & d & f & \end{bmatrix}$$

En `Python` usamos la función `transpose`:

In [55]:
np.transpose(A)

array([[1, 1, 1],
       [3, 0, 2],
       [2, 0, 2]])

#### Matriz inversa

Denomatamos con $A^{-1}$ la matriz inversa de una  matriz cuadrada A, si se cumple que la multiplicación $A \times A^{-1}$ es igual a la matriz identidad $I$, es decir:

$$A × A^{-1} = A^{-1} × A = I$$

Esto implica que la matriz inversa puede no existir. En estos casos decimos que la matriz es singular. Por lo tanto, una matriz es singular, si y solo si, su *determinante* es nulo.

En `Python` calculamos el determinante usando la función `linalg.det`:

In [1]:
np.linalg.det(A)

NameError: name 'np' is not defined

y la inversa usando `np.linalg.inv`:

In [59]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  7.40148683e-17, -1.00000000e+00],
       [-1.00000000e+00, -5.00000000e-01,  1.50000000e+00]])

La matriz inversa tiene ciertas propiedades que serán útiles para algunas aplicaciones del curso:

- $(A^{-1})^{-1}=A$
- $(AB)^{-1}=B^{-1}A^{-1}$
- $(A^{-1})^T=(A^T)^{-1}$

### Operaciones con matrices

Al igual que con los *vectores*, podemos operar sobre matrices teniendo en cuenta ciertas reglas de operación.


#### Suma y resta

Cuando *sumamos* (restamos) dos matrices, el resultado es la suma (resta) de cada elemento de las matrices 

$$\begin{split}A + B =
\left[
\begin{array}{ccc}
    a_{11} & \cdots & a_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} & \cdots & a_{nk} \\
\end{array}
\right]
+
\left[
\begin{array}{ccc}
    b_{11} & \cdots & b_{1k} \\
    \vdots & \vdots & \vdots \\
    b_{n1} & \cdots & b_{nk} \\
\end{array}
\right]
:=
\left[
\begin{array}{ccc}
    a_{11} + b_{11} &  \cdots & a_{1k} + b_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} + b_{n1} &  \cdots & a_{nk} + b_{nk} \\
\end{array}
\right]\end{split}$$

$$\begin{split}A - B =
\left[
\begin{array}{ccc}
    a_{11} & \cdots & a_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} & \cdots & a_{nk} \\
\end{array}
\right]-
\left[
\begin{array}{ccc}
    b_{11} & \cdots & b_{1k} \\
    \vdots & \vdots & \vdots \\
    b_{n1} & \cdots & b_{nk} \\
\end{array}
\right]
:=
\left[
\begin{array}{ccc}
    a_{11} - b_{11} &  \cdots & a_{1k} - b_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} - b_{n1} &  \cdots & a_{nk} - b_{nk} \\
\end{array}
\right]\end{split}$$

Para sumar (restar) dos matrices, debemos  tener en cuenta que solo se pueden sumar o restar matrices que tengan el mismo orden. Por ejemplo, si tenemos una matriz A de dimensión 4x3 (4 filas y 3 columnas) solo podemos sumar (restar) una matriz con las mismas dimensiones  (4x3, 4 filas y 3 columnas).

En `Python`:

- Suma

In [48]:
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

- Resta

In [49]:
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

#### Multiplicación por un escalar

La *Multiplicación por un escalar* es una operación que toma a un número  $\kappa$ (un escalar), y una matriz $A$, para producir una nueva matriz donde cada elemento es multiplicado por el número $\kappa$.

$$\begin{split}\kappa A
\left[
\begin{array}{ccc}
    a_{11} &  \cdots & a_{1k} \\
    \vdots & \vdots  & \vdots \\
    a_{n1} &  \cdots & a_{nk} \\
\end{array}
\right]
=
\left[
\begin{array}{ccc}
    \kappa a_{11} & \cdots & \kappa a_{1k} \\
    \vdots & \vdots & \vdots \\
    \kappa a_{n1} & \cdots & \kappa a_{nk} \\
\end{array}
\right]\end{split}$$

En `Python`:


In [30]:
A * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [31]:
B * 3

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21]])

#### Producto matricial

La multiplicación de matrices generaliza la idea del producto interior  de vectores. Para poder multiplicar matrices el número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz. El resultado de esta multiplicación va a ser una matriz que tiene el mismo número de filas que la primera matriz y el número de columnas de la segunda matriz. Por ejemplo: 

$$ A_{n \times k} \times B_{k \times p} = C_{n \times p} $$

Es decir, si tenemos una matriz A de dimensión $n\times k$ y la multiplicamos por una matriz B de dimensión $k \times p$ , el resultado es una matriz C de dimensión $n \times p$.

Esto implica que la propiedad conmutativa no se cumple en el producto matricial, es decir, $AxB$ no es igual a $BxA$.

En `Python`, comenzamos definiendo una matriz A de dimensión $3 \times 4$:

In [61]:
A = np.arange(1, 13).reshape(3, 4) 
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

y una matriz B de dimensión $4 \times 2$:

In [62]:
B = np.arange(8).reshape(4,2)
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

El producto resulta en una matriz de dimensión $3\times 2$:

In [63]:
A.dot(B) 

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

Por otro lado, el producto de $B\times A$ arroja un error porque el numero de columnas de B no es igual al número de filas de A.

In [29]:
B.dot(A)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

Por otra parte, el elemento neutro del producto de matrices es la matriz identidad. Esto nos dice que cualquier matriz multiplicada por la matriz identidad  da como resultado la misma matriz. 


In [46]:
A.dot(I)

array([[1., 3., 2.],
       [1., 0., 0.],
       [1., 2., 2.]])

In [47]:
I.dot(B)

array([[1., 0., 5.],
       [7., 5., 0.],
       [2., 1., 1.]])

#### Traza

La traza es una operación  simple que solo esta definida para matrices **cuadradas**. La traza es la suma de los elementos de la diagonal de la matriz.

$$tr(A)=\sum_ {i=1}^n A_{ii}$$

La traza tiene ciertas propiedades útiles:

- Para $A\in \mathbb{R}^{n\times n}$, $tr(A)=tr(A^\intercal)$

- Para $A,B \in \mathbb{R}^{n\times n}$, $tr(A+B)=tr(A)+tr(B)$

- Para $A \in \mathbb{R}^{n\times n}$, $\gamma \in \mathbb{R}$, $tr(\gamma A)= \gamma tr(A)$

- Para $A, B$ tal que $AB$ sea una matriz cuadrada, $tr(AB)=tr(BA)$

- Para $A, B, C$ tal que $ABC$ sea una matriz cuadrada, $tr(ABC)=tr(BCA)=tr(CAB)$. Esto sin perdida de generalidad para multiplicación de más matrices.

#### Eigenvalores y eigenvectores

Para una matriz cuadrada $A$ de dimensión $n\times n$, decimos que el número $\lambda$ es un *eigenvalor* de $A$ y el vector $x$ es el *eigenvector* asociado, de forma que:

$$Ax=\lambda x,\ x \neq 0$$

Notemos que para cualquier eigenvector $x$ y escalar $c$, se cumple que: 

$$A(cx)=cAx=c\lambda x = \lambda (cx)$$

Por lo que $cx$ también es un eigenvector. Por este motivo, y para evitar tener infinitos eigenvectores, decimos que existe "el" eigenvector asociado a $\lambda$ y que este está normalizado para tener norma 1. 

Reescribiendo la expresión $Ax=\lambda x,\ x \neq 0$ como:

$$(\lambda I - A)x=0,\ x \neq 0$$

En donde $(\lambda I - A)x=0$ tiene una solución no trivial para $x$, solo si $(\lambda I - A)$ no es un espacio nulo. Esto es equivalente a que $(\lambda I - A)$ sea singular, es decir:

$$|(\lambda I - A)|=0$$

Utilizando propiedades de determinantes podemos expandir esta expresión en un polinomio de $\lambda$ de grado $n$, al que se conoce como polinomio característico de la matriz $A$.

Entonces tenemos que encontrar las $n$ raíces del polinomio característico $\lambda_1, \lambda_2, \cdots, \lambda_n$, que serán los eigenvalores de $A$.

Los eigenvectores correspondientes al eigenvalor $\lambda_i$ surgen de resolver el sistema de ecuaciones lineales: 

$$(\lambda_i I - A)x=0$$



En `Python` podemos utilizar la función `linalg.eig`:

In [81]:
A = np.array([[1, 2], 
              [2, 9]])

w,v=np.linalg.eig(a)
print('Eigenvalores:', w)
print('Eigenvectores', v)

Eigenvalores: [11.43008584  1.89947784 -4.32956368]
Eigenvectores [[ 0.28344454  0.64079241  0.00924407]
 [ 0.7616636  -0.32530671 -0.47772887]
 [ 0.5826901  -0.69538524  0.87845869]]


Los eigenvalores y los eigenvectores tienen ciertas propiedades que nos serán útiles para ciertas aplicaciones en el curso. Para todos los casos vamos a suponer que $A\in\mathbb{R}^{n\times n}$ y que tiene $\lambda_i, \cdots, \lambda_n$ eigenvalores:

- La traza de $A$ es igual a la suma de los eigenvalores:
$$tr(A)=\sum_{i=1}^n\lambda_i$$

- El determinante de $A$ es igual al producto de los eigenvalores:
$$|A|=\prod_{i=1}^n\lambda_i$$

- El rango de $A$ es igual al número de eigenvalores de $A$ diferentes de cero.

- Si $A$ es no singular con eigenvalor $\lambda$ y un eigenvector asociado $x$, entonces $1/\lambda$ es un eigenvalor de $A^{-1}$ con eigenvector asociado $x$. $A^{-1}x=(1/\lambda)x$.

- Los eigenvalores de una matriz diagonal $D=diag(d_1, d_2, \cdots, d_n)$ son los elementos de la diagonal $d_1, d_2, \cdots, d_n$.

- Si la matriz $A$ tiene $n$ eigenvectores linealmente independientes, podemos ordenar esos vectores para conformar una matriz $S$ que sea cuadrada e invertible:

    $$ AS = A \begin{bmatrix} x_1 & x_2 & \cdots & x_n \end{bmatrix} $$

    $$ = \begin{bmatrix} \lambda_1 x_1 & \lambda_2 x_2 & \cdots & \lambda_n x_n \end{bmatrix} $$

    $$ S \begin{bmatrix} \lambda_1 & 0 & \cdots & 0 \\ 0 & \lambda_2 & & 0 \\ \vdots & & \ddots & \vdots \\ 0 & \cdots & 0 & \lambda_n \end{bmatrix} = S\Lambda$$
    
donde $\Lambda$ es una matriz diagonal en donde los valores que no son cero corresponden a los eigenvalores de $A$. Como las columnas de $S$ son independientes, $S^{-1}$ existe y por ende podemos multiplicar a ambos lados de $AS=S\Lambda$ por $S^{-1}$:

    $$S^{-1}AS=\Lambda$$

    $$A=S\Lambda S^{-1}$$

## Ejercicios de repaso

Resuelva los siguientes problemas. Intente realizarlos primero sin ayuda de `Python` y luego verifique su solución con los comandos de `Python`.

1. Sea $A = \begin{bmatrix} 7 & 10 \\ 1 & -2 \end{bmatrix}$, $B = \begin{bmatrix} 3 & 0 \\ 8 & -1 \end{bmatrix}$. Encuentre:

    a. $A^{9}$

    b. $B^{5}$

    c. $C=AB$
    
2. Encuentre el ángulo entre los siguientes vectores en radianes y grados.

    a. $\begin{cases}
a=2i-1j+7k\\
b=i+2j
\end{cases}$
    
    b. $\begin{cases} a = \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} \\ b = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \end{cases}$

3. Halle el área del paralelogramo limitado por las rectas $x-2y=3$, $x-2y=10$, $2x+3y=-1$ y $2x+3y=-8$ a partir del cálculo de un determinante.

4. Halle el volumen del paralelepípedo  generado por los vectores $a=[2,-1,-2]$, $b=[1,2,-3]$ y $c=[-1,3,5]$ a partir del cálculo de un determinante.

 # Conclusión
 
 En este *cuaderno* hicimos una breve revisión sobre vectores y matrices, y su implementación en `Python` utilizando la librería **[Numpy](http://www.numpy.org/)**. Estas van a ser algunas de las funciones que necesitaremos para el desarrollo de buena parte de las actividades de este curso.
Al ser un resumen, no es exhaustivo, por lo que lo invitamos a a explorar por si mismo y leer las documentaciones de [`Python`](https://python-docs-es.readthedocs.io/es/3.9/index.html) y [Numpy](http://www.numpy.org/).