----------------------------------- ----------------------------------- ----------------------------------- 
----------------------------------- ESPACIO PARA BANNER DE LA MAESTRIA -----------------------------------
----------------------------------- ----------------------------------- ----------------------------------- 

# Descomposición en Valores Singulares. Interpretación Geométrica  y Ejercicios Teóricos.

Este *cuaderno* cubre detalles sobre el algebra de la descomposición en valores singulares. El objetivo del *cuaderno* es que aprenda el funcionamiento de la descomposición en valores singulares, y a construir e implementar este método. Al final encontrará ejercicios asociados a los contenidos del cuaderno para que los resuelva por su propia cuenta (no debe entregarlos).  Si tiene dudas sobre los contenidos o los ejercicios, consulte con el tutor.


**NO** es necesario editar el archivo o hacer una entrega. Sin embargo, los ejemplos contienen celdas con código ejecutable (`en gris`), que podrá modificar  libremente. Esta puede ser una buena forma de aprender nuevas funcionalidades del *cuaderno*, o experimentar variaciones en los códigos de ejemplo.

## Interpretación geométrica

En el cuaderno *Descomposición en Valores Singulares. Fundamentos Teóricos.* mostramos que la SVD es la factorizacion de una matriz en 3 matrices. Entonces si tenemos una matrix real $X$ de dimensión $n\times k$, entonces su SVD esta representada por:

\begin{align}
\underset{n\times k}{\underbrace{X}}=\underset{n\times n}{\underbrace{U}}\underset{n\times k}{\underbrace{S}}\underset{k\times k}{\underbrace{V'}}
\end{align}

donde $U$ es una matriz $n\times n$ cuyas columnas son ortogonales $(U'U=I_{n})$, $V$ es una matriz $k\times k$ cuyas filas y columnas son también ortogonales $(V'V=VV'=I_{k})$, y $S$ es una matriz $n\times k$ que contiene los $r=min(n,k)$ valores singulares $(\sigma_{i}\geq0)$ en la diagonal principal, y 0 en el resto de la matriz. 

A $U$ se la suele denominar como la matriz de vectores singulares izquierdos, S como los valores singulares, y $V$ como los valores singulares derechos.


Para ilustrar como funciona la descomposición geometricamente, supongamos que tenemos un círculo en 2 dimensiones, representado por 2 vectores $v_1$ y $v_2$ como lo muestra la siguiente figura:

<div style="max-width:500px">
<img src = "figs/rot1.png" />
</div>

La SVD implica aplicar una transformación matricial a estos dos vectores de forma tal que vamos a obtener dos nuevos vectores $\sigma_1 u_1$ y $\sigma_2 u_2$:

\begin{align}
XV=US 
\end{align}
donde V es la matriz cuyas columnas son los vectores $v_1$ y $v_2$, $X$ es la matriz de datos, S la matriz diagonal de $\sigma_1$ y $\sigma_2$ y U la matriz de los vectores $u_1$ y $u_2$. Esta transformación equivale a "estirar" el círculo como lo muestra la siguiente figura:

<div style="max-width:500px">
<img src = "figs/rot2.png" />
</div>

En este caso los valores singulars $\sigma$ son los factores que estiran. Notemos además que las columnas de $V$ son ortogonales, por lo que podemos hacer:

\begin{align}
XV&=US \\
XVV'&=USV' \\
X &=USV'
\end{align}

donde obtenemos la expresion original. 

### Ejemplo

Miremos un ejemplo sencillo para illustrar el cálculo de SVD. Comenzamos con la siguiente matriz $X$:


\begin{align}
X=\left(\begin{array}{cc}
7 & 3\\
3 & -1
\end{array}\right)
\end{align}

partiendo de la ecuación $(X-\lambda I)x=0$, podemos obtener el polinomio
característico,

\begin{align}
\lambda^{2}-6\lambda+16=0
\end{align}

resolviendo tenemos que los eigenvalues son

\begin{align}
\lambda_{1}=8
\end{align}

y 

\begin{align}
\lambda_{2}=-2
\end{align}

luego necesitamos los eigenvectores. El eigenvector asociado con $\lambda_{1}=8$,
será

\begin{align}
Xv^{1}=\lambda_{1}v^{1}
\end{align}

\begin{align}
\left(X-\lambda_{1}I\right)v^{1}=0
\end{align}

\begin{align}
\left(\left(\begin{array}{cc}
7 & 3\\
3 & -1
\end{array}\right)-\left(\begin{array}{cc}
\lambda_{1} & 0\\
0 & \lambda_{1}
\end{array}\right)\right)v^{1}=0
\end{align}

\begin{align}
\left(\begin{array}{cc}
-1 & 3\\
3 & -9
\end{array}\right)\left(\begin{array}{c}
v_{1}^{1}\\
v_{2}^{2}
\end{array}\right)=0
\end{align}

\begin{align}
-1v_{11}+3v_{21}=0
\end{align}

\begin{align}
3v_{11}-9v_{21}=0
\end{align}

Entonces podemos ver que $v_{1}^{1}=3v_{2}^{1}$ , sin perdida de
generalidad podemos fijar $v_{2}^{1}=1$, entonces el eigenvector
asociado a este eigenvalor es 

\begin{align}
v^{1}=\left(\begin{array}{c}
3\\
1
\end{array}\right)
\end{align}

Normalizando para que el vector tenga dimensión 1 (dividimos por $\sqrt{3^{2}+1^{2}}$)

\begin{align}
v^{1}=\left(\begin{array}{c}
0.9486\\
0.3162
\end{array}\right)
\end{align}

Del mismo modo procedemos para el eigenvector asociado con $\lambda_{2}=-2$,
será

\begin{align}
\left(X-\lambda_{2}I\right)v^{2}=0
\end{align}

\begin{align}
\left(\left(\begin{array}{cc}
7 & 3\\
3 & -1
\end{array}\right)-\left(\begin{array}{cc}
\lambda_{2} & 0\\
0 & \lambda_{2}
\end{array}\right)\right)v^{2}=0
\end{align}

\begin{align}
\left(\begin{array}{cc}
9 & 3\\
3 & 1
\end{array}\right)\left(\begin{array}{c}
v_{1}^{2}\\
v_{2}^{2}
\end{array}\right)=0
\end{align}

\begin{align}
9v_{1}^{2}+3v_{2}^{2}=0
\end{align}

\begin{align}
3v_{1}^{2}-1v_{2}^{2}=0
\end{align}

De este sistema de ecuaciones podemos ver que $-3v_{1}^{2}=v_{2}^{2}$
, y fijando $v_{1}^{2}=1$, tenemos el eigenvector normalizado asociado

\begin{align}
v^{2}=\left(\begin{array}{c}
0.3162\\
-0.9486
\end{array}\right)
\end{align}

Recordando del cuaderno de *Descomposición en Valores Singulares. Fundamentos Teóricos.* la conexión entre SVD y eigenvalores,  podemos obtener la matriz $S$:

\begin{align}
S=\left(\begin{array}{cc}
8 & 0\\
0 & 2
\end{array}\right)
\end{align}

y la matriz V

\begin{align}
V=\left(\begin{array}{cc}
0.9486 & 0.3162\\
0.3162 & -0.9486
\end{array}\right)
\end{align}

Para completar la SVD $(X=USV')$ necesitamos computar $U$, o cual podemos hacer con la formula $\sigma_{i}u^{i}=Xv^{1}$

\begin{align}
u^{1}=\frac{1}{8}\left(\begin{array}{cc}
7 & 3\\
3 & -1
\end{array}\right)\left(\begin{array}{c}
0.9486\\
0.3162
\end{array}\right)=\left(\begin{array}{c}
0.9486\\
0.3162
\end{array}\right)
\end{align}

\begin{align}
u^{2}=\left(\frac{1}{2}\right)\left(\begin{array}{cc}
7 & 3\\
3 & -1
\end{array}\right)\left(\begin{array}{c}
0.3162\\
-0.9486
\end{array}\right)=\left(\begin{array}{c}
0.3162\\
-0.9486
\end{array}\right)
\end{align}

Con esto podemos completar $U$

\begin{align}
\left(\begin{array}{cc}
0.9486 & 0.3162\\
0.3162 & -0.9486
\end{array}\right)
\end{align}

Note, que en este caso nos dio una matriz igual a $V$. Rara vez tendremos que resolver esta descomposición con papel y lapiz, lo haremos generalmente en `Python`. Verifiquemos entonces, los resultados obtenidos en `Python`:

In [1]:
import numpy as np # llamamos numpy

X = np.array([[7, 3], 
              [3, -1]])

X

array([[ 7,  3],
       [ 3, -1]])

In [2]:
U, S, V = np.linalg.svd(X)

In [3]:
print('U=', U)

U= [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]


In [4]:
print('S=', S)

S= [8. 2.]


In [5]:
print('V=', V)

V= [[-0.9486833  -0.31622777]
 [ 0.31622777 -0.9486833 ]]


Note que los resultados son los mismos excepto por el cambio de signo. Esto tiene que ver con cómo computa `Python` los eigenvectos. Con estos podemos entonces reconstruir $X$ usando la ecuación $X =USV'$

In [6]:
X_reconstruida = U @ np.diag(S) @ V
X_reconstruida

array([[ 7.,  3.],
       [ 3., -1.]])

Podemos tambien verificar la relación entre SVD y eigenvalores:

In [7]:
eig_val, eig_vec = np.linalg.eig(X@X.T)
eig_val
np.sqrt(eig_val)

array([8., 2.])

## Ejercicios teóricos


Resuelva los siguientes problemas. Intente realizarlos primero sin ayuda de `Python` y luego verifique su solución con los comandos de `Python`.

1. Demuestre que la Descomposición en Valores Singulares encuentra la dirección para la cual la matriz original estira más el vector unitario. Parta de la siguiente expresión:
$$argmax_{x:||x||=1} ||Bx||$$
2. $B$ es una matriz cuadrada de tamaño $m\times m$, cuyas filas son ortonormales. Demuestre que las columnas de $B$ también son ortonormales.
3. Suponga que $C$ es una matriz cuadrada invertible y que la Descomposición en Valores Singulares de $C$ es $C=\sum_i \sigma_i u_i v_i'$. Encuentre la inversa de $C$.
4. Encuentre la SVD de la matriz $A$, $U S V'$, en donde $A = \begin{bmatrix} 3 & 2 & 2 \\ 2 & 3 & -2 \end{bmatrix}$
5. Demuestre que los vectores singulares izquierdos de una matriz $D$ son los vectores singulares derechos de $D'$
