# Revisión de Algebra Lineal

## Topicos

- Generaldades de Matrices
- Matrices en Python
- Determinantes
- Eigenvalues y eigenvectors (Autovalores y Autovectores)
- Trazas

## Introducción

Una de las herramientas matemáticas más utilizadas en [machine learning](http://es.wikipedia.org/wiki/Machine_learning) y [data mining](http://es.wikipedia.org/wiki/Miner%C3%ADa_de_datos) es el [Álgebra lineal](http://es.wikipedia.org/wiki/%C3%81lgebra_lineal); por tanto, si queremos incursionar en el fascinante mundo del aprendizaje automático y el análisis de datos es importante reforzar los conceptos que forman parte de sus cimientos. 

El [Álgebra lineal](http://es.wikipedia.org/wiki/%C3%81lgebra_lineal) es una rama de las [matemáticas](http://es.wikipedia.org/wiki/Matem%C3%A1ticas) que es sumamente utilizada en el estudio de una gran variedad de ciencias, como ser, ingeniería, finanzas, investigación operativa, entre otras. Es una extensión del [álgebra](http://es.wikipedia.org/wiki/%C3%81lgebra) que aprendemos en la escuela secundaria, hacia un mayor número de dimensiones; en lugar de trabajar con incógnitas a nivel de <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a> comenzamos a trabajar con <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a> y [vectores](http://es.wikipedia.org/wiki/Vector).  

El estudio del [Álgebra lineal](http://es.wikipedia.org/wiki/%C3%81lgebra_lineal) implica trabajar con varios objetos matemáticos, como ser:

* **Los <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">Escalares</a>**: Un *escalar* es un solo número, en contraste con la mayoría de los otros objetos estudiados en [Álgebra lineal](http://es.wikipedia.org/wiki/%C3%81lgebra_lineal), que son generalmente una colección de múltiples números.

* **Los [Vectores](http://es.wikipedia.org/wiki/Vector)**: Un *vector* es una serie de números. Los números tienen una orden preestablecido, y podemos identificar cada número individual por su índice en ese orden. Podemos pensar en los  *vectores* como la identificación de puntos en el espacio, con cada elemento que da la coordenada a lo largo de un eje diferente. Existen dos tipos de *vectores*, los *vectores de fila* y los *vectores de columna*. Podemos representarlos de la siguiente manera, dónde *f* es un vector de fila y *c* es un vector de columna:

$$ f = \begin{bmatrix} 0 & 1 & -1 \end{bmatrix} ;\ c= \begin{bmatrix} 0\\ 1 \\ -1 \end{bmatrix} $$

* **Las <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">Matrices</a>**: Una *matriz* es un arreglo bidimensional de números (llamados entradas de la matriz) ordenados en filas (o renglones) y columnas, donde una fila es cada una de las líneas horizontales de la matriz y una columna es cada una de las líneas verticales. En una *matriz* cada elemento puede ser identificado utilizando dos índices, uno para la fila y otro para la columna en que se encuentra. Las podemos representar de la siguiente manera, *A* es una matriz de 3x2.
$$A=\begin{bmatrix}0 & 1& \\-1 & 2 \\ -2 & 3\end{bmatrix}$$

* **Los [Tensores](http://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial)**: En algunos casos necesitaremos una matriz con más de dos ejes. En general, una serie de números dispuestos en una cuadrícula regular con un número variable de ejes es conocido como un *tensor*.

Sobre estos objetos podemos realizar las operaciones matemáticas básicas, como ser [adición](http://es.wikipedia.org/wiki/Adici%C3%B3n), [multiplicación](http://es.wikipedia.org/wiki/Multiplicaci%C3%B3n), [sustracción](http://es.wikipedia.org/wiki/Sustracci%C3%B3n) y <a href="http://es.wikipedia.org/wiki/Divisi%C3%B3n_(matem%C3%A1tica)" >división</a>, es decir que vamos a poder sumar [vectores](http://es.wikipedia.org/wiki/Vector) con <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a>, multiplicar <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a> a [vectores](http://es.wikipedia.org/wiki/Vector) y demás.

## Librerías de Python para álgebra lineal

Los principales módulos que [Python](http://python.org/) nos ofrece para realizar operaciones de [Álgebra lineal](http://es.wikipedia.org/wiki/%C3%81lgebra_lineal) son los siguientes:

* **[Numpy](http://www.numpy.org/)**: El popular paquete matemático de [Python](http://python.org/), nos va a permitir crear *[vectores](http://es.wikipedia.org/wiki/Vector)*, *<a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a>* y *[tensores](http://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial)* con suma facilidad.

* **[numpy.linalg](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html)**: Este es un submodulo dentro de [Numpy](http://www.numpy.org/) con un gran número de funciones para resolver ecuaciones de [Álgebra lineal](http://es.wikipedia.org/wiki/%C3%81lgebra_lineal).

* **[scipy.linalg](http://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html)**: Este submodulo del paquete científico [Scipy](http://docs.scipy.org/doc/scipy/reference/index.html) es muy similar al anterior, pero con algunas más funciones y optimaciones.

* **[Sympy](http://www.sympy.org/es/)**: Esta librería nos permite trabajar con matemática simbólica, convierte a [Python](http://python.org/) en un [sistema algebraico computacional](http://es.wikipedia.org/wiki/Sistema_algebraico_computacional). Nos va a permitir trabajar con ecuaciones y fórmulas simbólicamente, en lugar de numéricamente.

* **[CVXOPT](http://cvxopt.org/)**: Este módulo nos permite resolver problemas de optimizaciones de [programación lineal](http://es.wikipedia.org/wiki/Programaci%C3%B3n_lineal). 

* **[PuLP](http://pythonhosted.org//PuLP/)**: Esta librería nos permite crear modelos de [programación lineal](http://es.wikipedia.org/wiki/Programaci%C3%B3n_lineal) en forma muy sencilla con [Python](http://python.org/).

## Operaciones básicas

### Vectores

Un *[vector](http://es.wikipedia.org/wiki/Vector)* de largo `n` es una secuencia (o *array*, o *tupla*) de `n` números. La solemos escribir como x=(x1,...,xn) o x=[x1,...,xn]

En [Python](http://python.org/), un *[vector](http://es.wikipedia.org/wiki/Vector)* puede ser representado con una simple *lista*, o con un *array* de [Numpy](http://www.numpy.org/); siendo preferible utilizar esta última opción.

In [28]:
# Vector como lista de Python
v1 = [2, 4, 6]
v1

[2, 4, 6]

In [29]:
# Vectores con numpy
import numpy as np

v2 = np.ones(3) # vector de solo unos.
v2

array([1., 1., 1.])

In [30]:
v3 = np.array([1, 3, 5]) # pasando una lista a las arrays de numpy
v3

array([1, 3, 5])

In [31]:
v4 = np.arange(1, 8) # utilizando la funcion arange de numpy
v4

array([1, 2, 3, 4, 5, 6, 7])

### Operaciones con vectores

Las operaciones más comunes que utilizamos cuando trabajamos con *[vectores](http://es.wikipedia.org/wiki/Vector)* son la *suma*, la *resta* y la *multiplicación por <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a>*.

Cuando *sumamos* dos *[vectores](http://es.wikipedia.org/wiki/Vector)*, vamos sumando elemento por elemento de cada
*[vector](http://es.wikipedia.org/wiki/Vector)*.

$$ \begin{split}x + y
=
\left[
\begin{array}{c}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{array}
\right]
+
\left[
\begin{array}{c}
     y_1 \\
     y_2 \\
    \vdots \\
     y_n
\end{array}
\right]
=
\left[
\begin{array}{c}
    x_1 + y_1 \\
    x_2 + y_2 \\
    \vdots \\
    x_n + y_n
\end{array}
\right]\end{split}$$

De forma similar funciona la operación de resta.

$$ \begin{split}x - y
=
\left[
\begin{array}{c}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{array}
\right]
-
\left[
\begin{array}{c}
     y_1 \\
     y_2 \\
    \vdots \\
     y_n
\end{array}
\right]
=
\left[
\begin{array}{c}
    x_1 - y_1 \\
    x_2 - y_2 \\
    \vdots \\
    x_n - y_n
\end{array}
\right]\end{split}$$

La *multiplicación por <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a>* es una operación que toma a un número $\gamma$, y a un *[vector](http://es.wikipedia.org/wiki/Vector)* $x$ y produce un nuevo *[vector](http://es.wikipedia.org/wiki/Vector)* donde cada elemento del vector $x$ es multiplicado por el número $\gamma$.

$$\begin{split}\gamma x
=
\left[
\begin{array}{c}
    \gamma x_1 \\
    \gamma x_2 \\
    \vdots \\
    \gamma x_n
\end{array}
\right]\end{split}$$

En [Python](http://python.org/):

In [32]:
# Ejemplo en Python
x = np.arange(1, 5)
y = np.array([2, 4, 6, 8])
x, y

(array([1, 2, 3, 4]), array([2, 4, 6, 8]))

In [33]:
# sumando dos arrays (vectores en numpy)
x + y

array([ 3,  6,  9, 12])

In [34]:
# Note que Python no permite realizar operaciones algebraicas entre dos listas de forma directa.
# Esta es una de las razones por las que preferimos utilizar arrays para hacer operaciones de
# álgebra lineal
[1, 2, 3, 4] + [2, 4, 6, 8]

[1, 2, 3, 4, 2, 4, 6, 8]

In [35]:
# restando dos vectores
x - y

array([-1, -2, -3, -4])

In [36]:
# multiplicando por un escalar
x * 2

array([2, 4, 6, 8])

In [37]:
y * 3

array([ 6, 12, 18, 24])

#### Producto escalar o interior

El [producto escalar](https://es.wikipedia.org/wiki/Producto_escalar) de dos *[vectores](http://es.wikipedia.org/wiki/Vector)* se define como la suma de los productos de sus elementos, suele representarse matemáticamente como < x, y > o x'y, donde x e y son dos vectores.

$$< x, y > = \sum_{i=1}^n x_i y_i$$

Dos *[vectores](http://es.wikipedia.org/wiki/Vector)* son <a href="https://es.wikipedia.org/wiki/Ortogonalidad_(matem%C3%A1ticas)">ortogonales</a> o perpendiculares cuando forman ángulo recto entre sí. Si el producto escalar de dos vectores es cero, ambos vectores son <a href="https://es.wikipedia.org/wiki/Ortogonalidad_(matem%C3%A1ticas)">ortogonales</a>.

Adicionalmente, todo [producto escalar](https://es.wikipedia.org/wiki/Producto_escalar) induce una [norma](https://es.wikipedia.org/wiki/Norma_vectorial) sobre el espacio en el que está definido, de la siguiente manera:

$$\| x \| = \sqrt{< x, x>} = \left( \sum_{i=1}^n x_i^2 \right)^{1/2}$$

En [Python](http://python.org/):

In [38]:
# Calculando el producto escalar de los vectores x e y
np.dot(x, y)

60

In [39]:
# o lo que es lo mismo, que:
sum(x * y)

60

In [40]:
# Calculando la norma del vector X
np.linalg.norm(x)

5.477225575051661

In [41]:
# otra forma de calcular la norma de x
np.sqrt(np.dot(x, x))

5.477225575051661

In [42]:
# vectores ortogonales
v1 = np.array([3, 4])
v2 = np.array([4, -3])

np.dot(v1, v2)

0

### Matrices

Las <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a> son una forma clara y sencilla de organizar los datos para su uso en operaciones lineales.

Una <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> `n × k` es una agrupación rectangular de números con n filas y k columnas; se representa de la siguiente forma:

$$\begin{split}A =
\left[
\begin{array}{cccc}
    a_{11} & a_{12} & \cdots & a_{1k} \\
    a_{21} & a_{22} & \cdots & a_{2k} \\
    \vdots & \vdots &  & \vdots \\
    a_{n1} & a_{n2} & \cdots & a_{nk}
\end{array}
\right]\end{split}$$

En la <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> A, el símbolo $a_{nk}$ representa el elemento  n-ésimo de la fila en la k-ésima columna. La <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> A también puede ser llamada un *[vector](http://es.wikipedia.org/wiki/Vector)* si cualquiera de n o k son iguales a 1. En el caso de n=1, A se llama un *[vector](http://es.wikipedia.org/wiki/Vector) fila*, mientras que en el caso de k=1 se denomina un *[vector](http://es.wikipedia.org/wiki/Vector) columna*.

Las <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a> se utilizan para múltiples aplicaciones y sirven, en particular, para representar los coeficientes de los sistemas de ecuaciones lineales o para representar transformaciones lineales dada una base. Pueden sumarse, multiplicarse y descomponerse de varias formas.

### Operaciones con matrices

Al igual que con los *[vectores](http://es.wikipedia.org/wiki/Vector)*, que no son más que un caso particular, las <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a> se pueden *sumar*, *restar* y la *multiplicar por <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a>*.

Multiplicacion por escalares:
$$\begin{split}c A
\left[
\begin{array}{ccc}
    a_{11} &  \cdots & a_{1k} \\
    \vdots & \vdots  & \vdots \\
    a_{n1} &  \cdots & a_{nk} \\
\end{array}
\right]
=
\left[
\begin{array}{ccc}
    c a_{11} & \cdots & c a_{1k} \\
    \vdots & \vdots & \vdots \\
    c a_{n1} & \cdots & c a_{nk} \\
\end{array}
\right]\end{split}$$

Suma de matrices: $$\begin{split}A + B =
\left[
\begin{array}{ccc}
    a_{11} & \cdots & a_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} & \cdots & a_{nk} \\
\end{array}
\right]
+
\left[
\begin{array}{ccc}
    b_{11} & \cdots & b_{1k} \\
    \vdots & \vdots & \vdots \\
    b_{n1} & \cdots & b_{nk} \\
\end{array}
\right]
:=
\left[
\begin{array}{ccc}
    a_{11} + b_{11} &  \cdots & a_{1k} + b_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} + b_{n1} &  \cdots & a_{nk} + b_{nk} \\
\end{array}
\right]\end{split}$$

Resta de matrices: $$\begin{split}A - B =
\left[
\begin{array}{ccc}
    a_{11} & \cdots & a_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} & \cdots & a_{nk} \\
\end{array}
\right]-
\left[
\begin{array}{ccc}
    b_{11} & \cdots & b_{1k} \\
    \vdots & \vdots & \vdots \\
    b_{n1} & \cdots & b_{nk} \\
\end{array}
\right]
:=
\left[
\begin{array}{ccc}
    a_{11} - b_{11} &  \cdots & a_{1k} - b_{1k} \\
    \vdots & \vdots & \vdots \\
    a_{n1} - b_{n1} &  \cdots & a_{nk} - b_{nk} \\
\end{array}
\right]\end{split}$$

Para los casos de suma y resta, hay que tener en cuenta que solo se pueden sumar o restar <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matrices</a> que tengan las mismas dimensiones, es decir que si tengo una <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> A de dimensión 3x2 (3 filas y 2 columnas) solo voy a poder sumar o restar la <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> B si esta también tiene 3 filas y 2 columnas.

In [43]:
# Ejemplo en Python
# Para construir nuestra matriz creamos una lista de vectores fila.
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])

B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])

In [44]:
# suma de las matrices A y B
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [45]:
# resta de matrices
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [46]:
# multiplicando matrices por escalares
A * 2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [47]:
B * 3

array([[ 3,  0, 15],
       [21, 15,  0],
       [ 6,  3,  3]])

In [48]:
# ver la dimension de una matriz (filas, columnas)
A.shape

(3, 3)

In [49]:
# ver cantidad de elementos de una matriz
A.size

9

#### Multiplicacion o Producto de matrices

La regla para la [multiplicación de matrices](https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices) generaliza la idea del [producto interior](https://es.wikipedia.org/wiki/Producto_escalar) que vimos con los [vectores](http://es.wikipedia.org/wiki/Vector); y esta diseñada para facilitar las operaciones lineales básicas.
Cuando [multiplicamos matrices](https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices), el número de columnas de la primera <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> debe ser igual al número de filas de la segunda <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a>; y el resultado de esta multiplicación va a tener el mismo número de filas que la primer <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> y el número de la columnas de la segunda <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a>. Es decir, que si yo tengo una <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> A de dimensión 3x4 y la multiplico por una <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> B de dimensión 4x2, el resultado va a ser una <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> C de dimensión 3x2.

Algo a tener en cuenta a la hora de [multiplicar matrices](https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices) es que la propiedad [connmutativa](https://es.wikipedia.org/wiki/Conmutatividad) no se cumple. AxB no es lo mismo que BxA.

Veamos los ejemplos en [Python](http://python.org/).

In [50]:
# Ejemplo multiplicación de matrices
A = np.arange(1, 13).reshape(3, 4) #matriz de dimension 3x4
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
B = np.arange(8).reshape(4,2) #matriz de dimension 4x2
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [52]:
# Multiplicando A x B
A.dot(B) #resulta en una matriz de dimension 3x2

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [54]:
# Multiplicando B x A
B.dot(A)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

#### La matriz identidad,  la matriz inversa, y  la matrix transpuesta

La [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) es el elemento neutro en la [multiplicación de matrices](https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices), es el equivalente al número 1. Cualquier matriz multiplicada por la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) nos da como resultado la misma matriz. La [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) es una [matriz cuadrada](https://es.wikipedia.org/wiki/Matriz_cuadrada) (tiene siempre el mismo número de filas que de columnas); y su diagonal principal se compone de todos elementos 1 y el resto de los elementos se completan con 0. Suele representase con la letra I

Por ejemplo la matriz identidad de 3x3 sería la siguiente:

$$I=\begin{bmatrix}1 & 0 & 0 & \\0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix}$$



In [55]:
# Creando una matriz identidad de 2x2
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

Ahora que conocemos el concepto de la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad), podemos llegar al concepto de la [matriz inversa](https://es.wikipedia.org/wiki/Matriz_invertible). Si tenemos una matriz A, la [matriz inversa](https://es.wikipedia.org/wiki/Matriz_invertible) de A, que se representa como $A^{-1}$ es aquella [matriz cuadrada](https://es.wikipedia.org/wiki/Matriz_cuadrada) que hace que la multiplicación $A \times A^{-1}$ sea igual a la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) I. Es decir que es la <a href="http://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)">matriz</a> recíproca de A.

$$A × A^{-1} = A^{-1} × A = I$$

Tener en cuenta que esta [matriz inversa](https://es.wikipedia.org/wiki/Matriz_invertible) en muchos casos puede no existir. En este caso se dice que la matriz es singular o degenerada. Una matriz es singular si y solo si su <a href="https://es.wikipedia.org/wiki/Determinante_(matem%C3%A1tica)">determinante</a> es nulo.

El <a href="https://es.wikipedia.org/wiki/Determinante_(matem%C3%A1tica)">determinante</a> es un número especial que puede calcularse sobre las [matrices cuadradas](https://es.wikipedia.org/wiki/Matriz_cuadrada). Se calcula como la suma de los productos de las diagonales de la matriz en una dirección menos la suma de los productos de las diagonales en la otra dirección. El determinante de la matriz $A$ Se representa como $|A|$.

$$A=\begin{bmatrix}a_{11} & a_{12} & a_{13} & \\a_{21} & a_{22} & a_{23} & \\ a_{31} & a_{32} & a_{33} & \end{bmatrix}$$

$$|A| = 
     (a_{11} a_{22} a_{33} 
   + a_{12} a_{23} a_{31} 
   + a_{13} a_{21} a_{32} )
   - (a_{31} a_{22} a_{13} 
   + a_{32} a_{23} a_{11} 
   + a_{33} a_{21} a_{12})
 $$

A continuación se presentan algunas propiedades de la inversa. Para todos los ejemplos suponga que $A, B \in \mathbb{R}^{n\times n}$$ son no singulares.
- $(A^{-1})^{-1}=A$
- $(AB)^{-1}=B^{-1}A^{-1}$
- $(A^{-1})^\intercal=(A^\intercal)^{-1}$

In [56]:
# Multiplicar una matriz por la identidad nos da la misma matriz
A = np.array([[4, 7],
              [2, 6]])
A

array([[4, 7],
       [2, 6]])

In [57]:
A.dot(I) # AxI = A

array([[4., 7.],
       [2., 6.]])

In [58]:
# Calculando el determinante de la matriz A
np.linalg.det(A)

10.000000000000002

In [59]:
# Haciendo los cálculos manualmente obtendríamos
(4*6) - (7*2)

10

In [60]:
# Calculando la inversa de A.
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [61]:
# A x A_inv nos da como resultado I.
A.dot(A_inv)

array([[ 1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00]])

Por último, la [matriz transpuesta](http://es.wikipedia.org/wiki/Matriz_transpuesta) es aquella en que las filas se transforman en columnas y las columnas en filas. Se representa con el símbolo $A^\intercal$

$$\begin{bmatrix}a & b & \\c & d & \\ e & f & \end{bmatrix}^T:=\begin{bmatrix}a & c & e &\\b & d & f & \end{bmatrix}$$

Ejemplos en [Python](http://python.org/):

In [62]:
# Trasponiendo una matriz
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [63]:
np.transpose(A)

array([[0, 2, 4],
       [1, 3, 5]])

#### Traza
La traza de una matriz cuadrada $A\in \mathbb{R}^{n\times n}$ es la suma de los elementos de la diagonal de la matriz.

$$tr(A)=\sum_ {i=1}^n A_{ii}$$

La traza cuenta con las siguientes propiedades:
- Para $A\in \mathbb{R}^{n\times n}$, $tr(A)=tr(A^\intercal)$
- Para $A,B \in \mathbb{R}^{n\times n}$, $tr(A+B)=tr(A)+tr(B)$
- Para $A \in \mathbb{R}^{n\times n}$, $\gamma \in \mathbb{R}$, $tr(\gamma A)= \gamma tr(A)$
- Para $A, B$ tal que $AB$ sea una matriz cuadrada, $tr(AB)=tr(BA)$
- Para $A, B, C$ tal que $ABC$ sea una matriz cuadrada, $tr(ABC)=tr(BCA)=tr(CAB)$. Esto sin perdida de generalidad para multiplicación de más matrices.

#### Norma de un vector
La norma de un vector x (expresada como $||x||$) es una medida informal de la longitud del vector. Usalmente se utiliza la norma Euclideana o la norma $l_2$ la cual se define como:
$$||x||_2= \sqrt{\sum_{i=1}^nx_i^2}$$ 

Note que $||x||_2^2=x^Tx$

Más formalmente, decimos que una norma es una función $f: \mathbb{R}^n \rightarrow \mathbb{R}$ que satisface las siguientes cuatro propiedades:
1. **No negativa.** Para todo $x\in\mathbb{R}^n,\ f(x)\geq0$.
2. **Definida.** $f(x)=0$ si y solo si $x=0$.
3. **Homogeneidad.** Para todo $x\in\mathbb{R}^n,\ c\in\mathbb{R},\ f(cx)=|c|f(x)$
4. **Desigualdad triangular.** Para todo $x, y \in\mathbb{R}^n,\ f(x+y)\leq f(x) + f(y)$

Otro ejemplo de norma es la norma $l_1$:

$$||x||_1= |\sum_{i=1}^nx_i^2|$$

#### Eigenvalores y eigenvectores
Para una matriz cuadrada $A\in \mathbb{R}^{n\times n}$, decimos que $\lambda \in \mathbb{C}$ es un **[eigenvalor](https://es.wikipedia.org/wiki/Vector,_valor_y_espacio_propios)** de $A$ y $x\in \mathbb{C}^n$ es el **[eigenvector](https://es.wikipedia.org/wiki/Vector,_valor_y_espacio_propios)** (o vector propio) asociado si:
$$Ax=\lambda x,\ x \neq 0$$

Intuitivamente esta definición nos dice que si multiplicamos la matriz $A$ por un vector $x$ el resultado es un nuevo vector que apunta hacia la misma dirección que $x$, pero escalado por un factor de $\lambda$. Las transformaciones lineales en el espacio $\mathbb{R}^2$ son la rotación, la reflexión, el escalado uniforme y la proyección sobre una recta. Por tal motivo, una aplicación inmediata de este tópico se halla en la transformación de imágenes digitales.

Note que para cualquier eigenvector $x\in \mathbb{C}^n$ y escalar $c \in \mathbb{C}$, $A(cx)=cAx=c\lambda x = \lambda (cx)$, por lo que $cx$ también es un eigenvector. Por tal motivo, para evitar tener infinitos eigenvectores, decimos que existe "el" eigenvector asociado a $\lambda$ y este está normalizado para tener norma 1. (Esto todavía nos genera una ambiguedad pues $x$ y $-x$ son ambos eigenvectores, pero debemos convivir con ello).

Podemos re escribir la expresión $Ax=\lambda x,\ x \neq 0$ como:

$$(\lambda I - A)x=0,\ x \neq 0$$

En donde, $(\lambda I - A)x=0$ tiene una solución no trivial para $x$ solo si $(\lambda I - A)$ no es un espacio nulo, lo cual es lo mismo que $(\lambda I - A)$ sea singular, es decir:

$$|(\lambda I - A)|=0$$

Aquí podemos usar la definición del determinante para expandir la expresión pasada en un polinomio de $\lambda$, en donde $\lambda$ tendrá grado $n$. A esto usualmente se le llama el polinomio característico de la matriz $A$.

Debemos encontrar las $n$ raíces del polinomio característico. Las denotaremos como $\lambda_1, \lambda_2, \cdots, \lambda_n$. Cada uno de estos valores será un eigenvalor de la matriz $A$.

Para encontrar el eigenvector correspondiente al eigenvalor $\lambda_i$ se debe solucionar el sistema de ecuaciones lineal $(\lambda_i I - A)x=0$. Aquí sabemos que tendremos una solución diferente a la trivial pues $\lambda_i I - A$ es singular (sin embargo podrían haber varias o infinitas soluciones).

A continuación se presentan algunas propiedades de los eigenvalores y los eigenvectores. Para todos los casos suponga que $A\in\mathbb{R}^{n\times n} tiene $\lambda_i, \cdots, \lambda_n$ eigenvalores):
- La traza de $A$ es igual a la suma de los eigenvalores.
$$tr(A)=\sum_{i=1}^n\lambda_i$$
- El determinante de $A$ es igual al producto de los eigenvalores:
$$|A|=\prod_{i=1}^n\lambda_i$$
- El rango de $A$ es igual al número de eigenvalores de $A$ diferentes de cero.
- Suponga que $A$ es no singular con eigenvalor $\lambda$ y un eigenvector asociado $x$. Entonces $1/\lambda$ es un eigenvalor de $A^{-1}$ con eigenvector asociado $x$. $A^{-1}x=(1/\lambda)x$.
- Los eigenvalores de una matriz diagonal $D=diag(d_1, d_2, \cdots, d_n)$ son los elementos de la diagonal $d_1, d_2, \cdots, d_n$.

In [65]:
# Aunque calcular los eigenvalores y los eigenvectores con papel y lapiz puede ser tedioso
# En Python solo necesitamos de la función eig del modulo linalg del paquete Numpy.
from numpy.linalg import eig
a = np.array([[1, 2], 
              [2, 9]])
w,v=eig(a)
print('Eigenvalores:', w)
print('Eigenvectores', v)

Eigenvalores: [0.52786405 9.47213595]
Eigenvectores [[-0.97324899 -0.22975292]
 [ 0.22975292 -0.97324899]]


In [66]:
a = np.array([[4, 2, 1], 
              [7, 5, 5],
              [2, 8, 0]])
w,v=eig(a)
print('Eigenvalores:', w)
print('Eigenvectores', v)

Eigenvalores: [11.43008584  1.89947784 -4.32956368]
Eigenvectores [[ 0.28344454  0.64079241  0.00924407]
 [ 0.7616636  -0.32530671 -0.47772887]
 [ 0.5826901  -0.69538524  0.87845869]]
