--- 
<center>
<h3> ESPACIO PARA BANNER DE LA MAESTRIA </h3> 
</center>

---

## Ejercicios teóricos
# Descomposición en Valores Singulares

1. Demuestre que la Descomposición en Valores Singulares encuentra la dirección para la cual la matriz original estira más el vector unitario. Parta de la siguiente expresión:
$$\argmax_{x:||x||=1} ||Bx||$$
2. $B$ es una matriz cuadrada de tamaño $m\times m$ la cual sus filas son ortonormales. Demuestre que las columnas de $B$ también son ortonormales.
3. Suponga que $C$ es una matriz cuadrada invertible y que la Descomposición en Valores Singulares de $C$ es $C=\sum_i \sigma_i u_i v_i^T$. Encuentre la inversa de $C$.
4. Encuentre la DVS o SVD de la matriz $A$, $U\Sigma V^T$, en donde $A = \begin{bmatrix} 3 & 2 & 2 \\ 2 & 3 & -2 \end{bmatrix}$
5. Demuestre que los vectores singulares izquierdos de una matriz $D$ son los vectores singulares derechos de $D^T$

---

---
### Solución punto 1.
Cambiemos el problema inicial a partir de elevar al cuadrado la expresión $||Ax||$. Sabemos que esto no debe cambiar la solución pues encontrar el vector $x$ que maximice el tamaño de su transformación también debe maximizar el tamaño de la transformación al cuadrado:
$$\argmax_{x:||x||=1} ||Ax||^2$$
Ahora procedemos a hacer algo de álgebra.
$$\argmax_{x:||x||=1} ||Ax||^2= \argmax_{x:||x||=1}\ (Ax)^T(Ax) = \argmax_{x:||x||=1}\ x^TA^TAx$$
Recordemos que podemos reescribir los últimos tres términos a partir de los eigenvalores asociados a la matriz A: $(A^TA)x=\lambda x$.
$$(A^TA)x=\lambda x$$
$$x^T(A^TA)x=\lambda x^T x$$
Como $x$ es un vector unitario sabemos que $x^T x=1$
Finalmente, tendríamos que: 
$$\argmax_{x:||x||=1}\ x^TA^TAx = \argmax_{x:||x||=1}\ \lambda$$
Es decir que para maximizar la longitud de la transformación $||Ax||$ debemos encontrar el eigenvector $x$ asociado al eigenvalor más grande.

---

### Solución punto 2.
Como las filas de $B$ son ortonormales entonces $BB^T=I$. Entonces, $B^TBB^T=B^T$. Dado que $B^T$ es no singular (pues tiene rango completo y es cuadrada), existe su inversa. Multiplicando a ambos lados de la expresión anterior por la inversa de $B$ obtenemos $B^TBB^T(B^T)^{-1}=B^T(B^T)^{-1}$, lo cual implica que las columnas de $B$ sean ortonormales:
$$B^TB=I$$

---

### Solución punto 3.
La SVD de $C$ puede escribirse como $C=U\Sigma V^T$, por ende la inversa puede ser calculada como:
$$C^{-1}=(U\Sigma V^T)^{-1}$$
$$C^{-1}=(V^T)^{-1}\Sigma^{-1}U^{-1}$$
Ahora, recordamos las propiedades de las matrices $U$ y $V$ las cuales son ortonormales, por ende sus traspuestas son sus inversas: $U^TU=UU^T=I$ y $V^TV=VV^T=I$.
$$C^{-1}=V\Sigma^{-1}U^T$$
Como $\Sigma$ es una matriz diagonal, su inversa es la misma matriz reemplazando cada elemento de la diagonal por su reciproco:
$$\begin{split} \Sigma^{-1} =
\left[
\begin{array}{cccc}
    \frac{1}{\sigma_1} & 0 & \cdots & 0 \\
    0 & \frac{1}{\sigma_2} & \cdots & 0 \\
    \vdots & \vdots & \ddots  & \vdots \\
    0 & 0 & \cdots & \frac{1}{\sigma_n}
\end{array}
\right]\end{split}$$
Resolviendo la multiplicación matricial obtenemos: $C^{-1}=\sum_i \frac{1}{\sigma_i} v_i u_i^T$

---

### Solución punto 4.
Primero vamos a encontrar los eigenvalores para construir $\Sigma$. Para esto vamos a construir la matriz $AA^T$:

$$\begin{split} AA^T =
\left[
\begin{array}{cc}
    17 & 8 \\
    8 & 17 \\
\end{array}
\right]\end{split}$$

El polinomo característica está dado por $det(AA^T-\lambda I)=\lambda^2-34\lambda+225=(\lambda-25)(\lambda-9)$. De tal modo obtenemos $\lambda_1=25$ y $\lambda_2=9$. Por tal motivo $\sigma_1=5$ y $\sigma_2=3$ serían los elementos de la diagonal de $\Sigma$.

Ahora vamos a encontrar los vectores singulares derechos (es decir las columnas de V) encontrando un set de eigenvectores ortonormales de $A^TA$. Sabemos que los eigenvalores de $A^TA$ serán los mismos que los de $AA^T$ y como $A^TA$ es simétrica sabemos que sus eigenvectores serán ortogonales.

Para $\lambda=25$, tenemos:

$$\begin{split} A^TA-25I =
\left[
\begin{array}{ccc}
    -12 & 12 & 2 \\
    12 & -12 & -2 \\
    2 & -2 & -17 \\
\end{array}
\right]\end{split}$$

Haciendo una reducción por filas obtenemos:
$$\begin{split} A^TA-25I =
\left[
\begin{array}{ccc}
    1 & -1 & 0 \\
    0 & 0 & 1 \\
    0 & 0 & 0 \\
\end{array}
\right]\end{split}$$

Un eigenvector de longitud 1 sería entonces $v_1=[1/\sqrt2, 1/\sqrt2, 0]$

Para $\lambda=9$ tenemos:
$$\begin{split} A^TA-9I =
\left[
\begin{array}{ccc}
    4 & 12 & 2 \\
    12 & 4 & -2 \\
    2 & -2 & -1 \\
\end{array}
\right]\end{split}$$

Haciendo una reducción por filas obtenemos:
$$\begin{split} A^TA-25I =
\left[
\begin{array}{ccc}
    1 & 0 & -1/4 \\
    0 & 1 & 1/4 \\
    0 & 0 & 0 \\
\end{array}
\right]\end{split}$$

Un eigenvector de longitud 1 sería entonces $v_2=[1/\sqrt18, -1/\sqrt18, 4/\sqrt18]$

Para el último eigenvector podemos hallarlo como lo venimos haciendo o encontrar un vector unitario perpendicular a $v_1 y v_2$. Para ser perpendicular a un vector $v_1=\begin{bmatrix} a \\ b \\ c \end{bmatrix}$ se necesita $-a=b$. Luego la condición para que $v_2^Tv_3=0$ se vuelve $2a/\sqrt18+4c/\sqrt18=0$ o $-a=2c$. Luego $v_3=[a, -a, -a/2]=[2/3,-2/3,-1/3]$

Finalmente, encontramos $U$ con la formula $\sigma u_i=Av_i \rightarrow u_i=\frac{1}{\sigma}Av_i$. Obtendríamos: 
 $$\begin{split} U =
\left[
\begin{array}{cc}
    1/\sqrt2 &  1/\sqrt2 \\
    1/\sqrt2 & - 1/\sqrt2 
\end{array}
\right]\end{split}$$

Finalmente, tendríamos como solución: 
$$A=U\Sigma V^T= \begin{bmatrix} 1/\sqrt2 &  1/\sqrt2 \\ 1/\sqrt2 & - 1/\sqrt2 \end{bmatrix} 
    \begin{bmatrix} 5 & 0 & 0 \\ 0 & 3 & 0 \end{bmatrix} 
    \begin{bmatrix} 1/\sqrt2 & 1/\sqrt2 & 0 \\ 1/\sqrt18 & -1/\sqrt18 & 4/\sqrt18 \\ 2/3 & -2/3 & -1/3 \end{bmatrix}$$

A continuación se comprueban los resultados con código:

In [1]:
import numpy as np

In [12]:
A = np.array([[3, 2, 2], [2, 3, -2]])
AAt = A @ A.transpose()
AtA = A.transpose() @ A  

In [15]:
print(A)
print(AAt)
print(AtA)

[[ 3  2  2]
 [ 2  3 -2]]
[[17  8]
 [ 8 17]]
[[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]


In [11]:
np.linalg.svd(AAt)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([25.,  9.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [14]:
np.linalg.svd(AtA)

(array([[-7.07106781e-01,  2.35702260e-01, -6.66666667e-01],
        [-7.07106781e-01, -2.35702260e-01,  6.66666667e-01],
        [ 2.43573286e-17,  9.42809042e-01,  3.33333333e-01]]),
 array([2.500000e+01, 9.000000e+00, 3.978288e-15]),
 array([[-7.07106781e-01, -7.07106781e-01, -1.65477681e-18],
        [ 2.35702260e-01, -2.35702260e-01,  9.42809042e-01],
        [ 6.66666667e-01, -6.66666667e-01, -3.33333333e-01]]))

In [21]:
U = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
S = np.array([[5, 0, 0], [0, 3, 0]])
Vt = np.array([[1/np.sqrt(2), 1/np.sqrt(2), 0], 
    [1/np.sqrt(18), -1/np.sqrt(18), 4/np.sqrt(18)],
    [2/3, -2/3, -1/3]])
U @ S @ Vt

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

---
### Solución punto 5

$D=U\Sigma V^T$

$D^T=(U\Sigma V^T)^T=V\Sigma U^T$

---